
; Autogenerated by the Meson build system.
; Do not edit, your changes will be lost.
;%define ARCH_X86_32 0
;%define ARCH_X86_64 0
;%define WIN64 0
;%define PIC 0
; %define STACK_ALIGNMENT 16 -- Stack alignment is controlled by Chromium
%define private_prefix dav1d
