#define VERSION_MAJOR  1
#define VERSION_MINOR  15
#define VERSION_PATCH  2
#define VERSION_EXTRA  "337f4bd"
#define VERSION_PACKED ((VERSION_MAJOR<<16)|(VERSION_MINOR<<8)|(VERSION_PATCH))
#define VERSION_STRING_NOSP "v1.15.2-337f4bd"
#define VERSION_STRING      " v1.15.2-337f4bd"
