#define VERSION_MAJOR  1
#define VERSION_MINOR  14
#define VERSION_PATCH  0
#define VERSION_EXTRA  "f394f2b"
#define VERSION_PACKED ((VERSION_MAJOR<<16)|(VERSION_MINOR<<8)|(VERSION_PATCH))
#define VERSION_STRING_NOSP "v1.14.0-f394f2b"
#define VERSION_STRING      " v1.14.0-f394f2b"
