#ifndef LIBCROCO_VERSION_NUMBER
//define LIBCROCO_VERSION_NUMBER v0.6.99
#endif

#ifndef LIBCROCO_VERSION
#define LIBCROCO_VERSION "0.6.99-b9e4b47"
#endif

/*#ifndef G_DISABLE_CHECKS
#if @G_DISABLE_CHECKS@
#define G_DISABLE_CHECKS @G_DISABLE_CHECKS@
#endif
#endif*/

#ifndef CROCO_HAVE_LIBXML2
#define CROCO_HAVE_LIBXML2 (1)
#endif
