#define _GLIB_EXTERN extern
#define _GIO_EXTERN extern
#define _GMODULE_EXTERN extern
#define GLIB_DEPRECATED G_DEPRECATED _GLIB_EXTERN
#define GLIB_DEPRECATED_FOR(f) G_DEPRECATED_FOR(f) _GLIB_EXTERN
#define GLIB_VAR _GLIB_EXTERN
#define GOBJECT_VAR _GLIB_EXTERN
#define GLIB_VERSION_MAX_ALLOWED GLIB_VERSION_2_82
#define GLIB_VERSION_MIN_REQUIRED GLIB_VERSION_2_26
#define GOBJECT_VERSION_MAX_ALLOWED GOBJECT_VERSION_2_82
#define GOBJECT_VERSION_MIN_REQUIRED GOBJECT_VERSION_2_26
#define GIO_VERSION_MAX_ALLOWED GIO_VERSION_2_82
#define GIO_VERSION_MIN_REQUIRED GIO_VERSION_2_26
#define GMODULE_VERSION_MAX_ALLOWED GMODULE_VERSION_2_82
#define GMODULE_VERSION_MIN_REQUIRED GMODULE_VERSION_2_26
#define GLIB_COMPILATION
#define GIO_COMPILATION
#define GOBJECT_COMPILATION
#define G_SETTINGS_ENABLE_BACKEND

#define USE_SYSTEM_PRINTF 1
#undef G_ATOMIC_LOCK_FREE
#define SIZEOF_WCHAR_T 2
#define G_ENABLE_DEBUG 1
#define G_OS_WIN32 1
#define G_PLATFORM_WIN32 1

/* Define to the GLIB major version */
#define GLIB_MAJOR_VERSION 2
/* Define to the GLIB minor version */
#define GLIB_MINOR_VERSION 81
/* Define to the GLIB micro version */
#define GLIB_MICRO_VERSION 0

#ifndef G_LIB_STATIC
#define G_LIB_EXPORT __declspec(dllexport)
#else
#define G_LIB_EXPORT extern
#endif
