#ifndef PANGO_FEATURES_H
#define PANGO_FEATURES_H

#define PANGO_VERSION_MAJOR 1
#define PANGO_VERSION_MINOR 51
#define PANGO_VERSION_MICRO 1

#define PANGO_VERSION_STRING "1.51.1-7217b2b"

#endif /* PANGO_FEATURES_H */
