#ifndef PANGO_FEATURES_H
#define PANGO_FEATURES_H

#define PANGO_VERSION_MAJOR 1
#define PANGO_VERSION_MINOR 51
#define PANGO_VERSION_MICRO 0

#define PANGO_VERSION_STRING "1.51.0-a6b4b77"

#endif /* PANGO_FEATURES_H */
