/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-XXXXXX-g9a245bdf5d"
#endif /* AVUTIL_FFVERSION_H */
